#!/usr/bin/env bash
# displays infomation about subdomains
# shellcheck disable=SC2086
domain="$1"
sub_domain="$2"
info () {
    if [ "$2" ]
    then
	dig "$2.$1" | awk -v sub_d="$2"  '/^'$2'/ {print "The subdomain", sub_d, "is a", $4, "record and points to", $5}'
    else
	dig "www.$1" | awk '/^www/{print "The subdomain www is a", $4, "record and points to", $5}'
	dig "lb-01.$1" | awk '/^lb-01/{print "The subdomain lb-01 is a", $4, "record and points to", $5}'
	dig "web-01.$1" | awk '/^web-01/{print "The subdomain web-01 is a", $4, "record and points to", $5}'
	dig "web-02.$1" | awk '/^web-02/{print "The subdomain web-02 is a", $4, "record and points to", $5}'
    fi
}

info $domain $sub_domain
