#!/usr/bin/env bash
# move a file from client to a remote server
if [ $# -le 3 ]
   then
       echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
