#!/usr/bin/env bash
# script installing and configuring nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html/
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
