#!/usr/bin/env bash
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
replace="rewrite \^\/redirect_me\$ https://www.google.com permanent;\n"
sudo sed -i  "s~# pass.*~$replace~"  /etc/nginx/sites-enabled/default
sudo service nginx restart
