#!/usr/bin/env bash
# configure nginx redirection
sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html/
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /etc/nginx/
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    rewrite ^/redirect_me\$ https://wwww.google.com permanent;
}" | tee /etc/nginx/sites-available/default

sudo service nginx restart
