#!/usr/bin/env bash
# configure nginx redirection
sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html/
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo chown -R "$USER":"$USER" /etc/nginx/
printf "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html/;
    index  index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://google.com/;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
