#!/usr/bin/env bash
# configure nginx redirection
sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html/
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo chown -R "$USER":"$USER" /etc/nginx/
printf "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html/;
    index  index.html index.htm index.nginx-debian.html 404.html;

    location / {
    	add_header X-Served-By \$hostname;
    }

    location /redirect_me {
        return 301 https://google.com/;
    }

    error_page 404 /404.html;
    location /404 {
       root /usr/share/nginx/html;
       internal;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
