#!/usr/bin/env bash
# installs and configure HAproxy on a new Ubuntu machine
sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y install haproxy=2.5.\*
sudo chown -R "$USER":"$USER" /etc/haproxy
sudo chown -R "$USER":"$USER" /etc/default/haproxy
echo "ENABLED=1" >> /etc/default/haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo printf '%s' "
frontend haproxy-main
    bind *:80
    mode http
    option forwardfor
    default_backend nginx_webservers    

backend nginx_webservers
    balance roundrobin
    server 33802-web-01	3.239.2.4:80 check
    server 33802-web-02	54.146.87.101:80 check
" | tee -a  /etc/haproxy/haproxy.cfg
sudo service haproxy start
