#!/usr/bin/env bash
# installs and configure HAproxy on a new Ubuntu machine
apt-get install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy

cp /etc/haproxy/haproxy.cfg /etc/haproxy/original.cfg

echo "
frontend front
        bind *:80
	default_backend web
backend web
        balance roundrobin
        server 33802-web-01 3.239.2.4:80 check
        server 33802-web-02 54.146.87.101:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart
