#!/usr/bin/env bash
# shellcheck disable=SC2034
# displays the content of the file /etc/passwd

file="/etc/passwd"

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
    # display fields using f1, f2,..,f7
    echo "$f1:$f3:$f6"
done < "$file"
