#!/usr/bin/env bash
# displays numbers from 1 to 20

n=1
while [ $n -le 20 ]
do
    case $n in
	4)
	    echo -e "$n\nbad luck from China"
	    ;;
	9)
	    echo -e "$n\nbad luck from Japan"
	    ;;
	17)
	    echo -e "$n\nbad luck from Italy"
	    ;;
	*)
	    echo "$n"
	    ;;
    esac
    (( ++n ))
done    
