#!/usr/bin/env bash
# shellcheck disable=SC2045,SC2154
# displays: The content of the current directory In a list format
# Where only the part of the name after the first
#+ dash is displayed

for list in $(ls)
do
    echo "$list" | sed "${s/.*-//}"
done    
